# NIVELL 1

In [27]:
import pandas as pd

## Exercici 1: Selecció de Personal

Tu treballes com a analista de dades en el departament de RRHH d'una empresa. S'ha obert una nova oferta laboral interna i l'empresa ha decidit que només les primeres 10 persones que s'inscriguin podran participar en el procés de selecció.
Per això, t'han encarregat desenvolupar una eina senzilla en Python que actuï com a formulari d'inscripció i sistema de classificació inicial. Aquest formulari ha de permetre introduir, per a cada candidat/a:

Nom i Cognoms
Telèfon de contacte
Anys d'experiència dins de l'empresa
Coneixement de Català (0–3 punts)
0 = sense coneixement
1 = fins a nivell B1
2 = nivell B2
3 = C1 o superior
Domini d'Excel (0–3 punts)
0 = nivell bàsic
1 = ús de funcions
2 = taules dinàmiques
3 = Visual Basic i Macros
Títol acadèmic (0–3 punts)
0 = ESO
1 = FP
2 = Universitat
3 = Màster o superior
Assegurant-se que tota la informació introduïda és correcta i entra dins els valors permesos. A partir d'aquestes dades, el programa haurà de calcular una puntuació total aplicant el pes de l'experiència (anys * 1.5) i sumant-hi els punts de català, excel i titulació, i a continuació classificar automàticament cada persona segons els llindars establerts per l'empresa:

» Prioritat Alta → puntuació ≥ 12
» Candidat adequat → 8 ≤ puntuació < 12
» No prioritari → puntuació < 8
Cada vegada que algú complet a el formulari, s'ha de mostrar la seva puntuació individual. Quan ja s'hagin inscrit exactament deu persones, l'eina ha de deixar d'acceptar nous registres i generar un informe final en pantalla, ordenat primer segons la prioritat i, en cas d'empat, per la puntuació obtinguda. Aquest informe ha d'incloure el nom, el telèfon i la puntuació de cada candidat per tal que el departament de RRHH els pugui contactar ràpidament.

🧠 **Algoritme inicial**

1. Preparar una estructura on guardar els candidats vàlids.
2. Demanar les dades d'un candidat mitjançant un formulari.
3. Validar les dades introduïdes i convertir a número les dades necessàries per als càlculs.
4. Si les dades no són vàlides, mostrar un missatge d'error i no comptar aquest registre com a candidat vàlid.
5. Si les dades són vàlides, calcular la puntuació total del candidat:
   - experiència × 1.5,
   - sumar punts de català,
   - sumar punts d'Excel,
   - sumar punts de titulació.
6. Classificar el candidat segons la puntuació obtinguda:
   - Prioritat Alta → puntuació ≥ 12,
   - Candidat adequat → 8 ≤ puntuació < 12,
   - No prioritari → puntuació < 8.
7. Mostrar la puntuació individual del candidat.
8. Guardar les dades, la puntuació i la classificació del candidat vàlid.
9. Repetir el procés fins a tenir exactament 10 candidats vàlids.
10. Quan hi hagi 10 candidats vàlids, deixar d'acceptar noves inscripcions.
11. Ordenar els candidats primer segons la prioritat i, en cas d'empat, segons la puntuació.
12. Mostrar l'informe final amb el nom, el telèfon i la puntuació de cada candidat.

**Interpretació:** aquesta funció fa de formulari. Recull totes les dades d'un sol candidat i les agrupa en un diccionari perquè la resta de funcions puguin treballar amb una única estructura.

🧩 **Desgranant el problema: naixement de les funcions**

✔ `obtenir_dades()`

1. Crear un diccionari buit per guardar les dades d'un candidat.
2. Demanar el nom i cognoms via `input` i guardar-los al diccionari.
3. Demanar el telèfon de contacte via `input` i guardar-lo al diccionari.
4. Demanar els anys d'experiència via `input` i guardar-los al diccionari.
5. Demanar el nivell de català, mostrant les opcions de 0 a 3, i guardar la resposta al diccionari.
6. Demanar el nivell d'Excel, mostrant les opcions de 0 a 3, i guardar la resposta al diccionari.
7. Demanar el nivell de titulació, mostrant les opcions de 0 a 3, i guardar la resposta al diccionari.
8. Retornar el diccionari amb totes les dades del candidat.

In [28]:
def obtenir_dades():

    dicc = {}

    dicc["nom"] = input("Escriu el teu nom i cognoms")
    dicc["telf"] = input("Escriu el teu telèfon de contacte")
    dicc["exp"] = input("Quants anys d'experiència tens dins l'empresa?")
    dicc["cat"] = input(
        "Coneixement de català:\n"
        "0 = Sense coneixement\n"
        "1 = Fins a nivell B1\n"
        "2 = Nivell B2\n"
        "3 = C1 o superior\n"
        "Escull una opció (0-3): ")
    dicc["excel"] = input(
        "Domini d'Excel:\n"
        "0 = nivell bàsic\n"
        "1 = ús de funcions\n"
        "2 = taules dinàmiques\n"
        "3 = Visual Basic i Macros\n"
        "Escull una opció (0-3): ")
    dicc["titol"] = input(
        "Títol acadèmic:\n"
        "0 = ESO\n"
        "1 = FP\n"
        "2 = Universitat\n"
        "3 = Màster o superior\n"
        "Escull una opció (0-3): ")

    return dicc

**Interpretació:** aquesta funció comprova si les dades numèriques es poden utilitzar correctament. Si es poden convertir a enters retorna `True`; si alguna conversió falla, retorna `False`.

✔ `validar_dades(p_dicc)`

1. Rebre com a paràmetre el diccionari d'un candidat.
2. Tractar de convertir a números enters les dades que després s'utilitzaran en els càlculs:
   - experiència,
   - català,
   - Excel,
   - titulació.
3. Si totes les conversions es poden fer correctament, retornar `True`.
4. Si alguna conversió provoca un `ValueError`, mostrar un missatge d'error i retornar `False`.

In [29]:
def validar_dades(p_dicc):

    try:
        p_dicc["exp"] = int(p_dicc["exp"])
        p_dicc["cat"] = int(p_dicc["cat"])
        p_dicc["excel"] = int(p_dicc["excel"])
        p_dicc["titol"] = int(p_dicc["titol"])

        if p_dicc["exp"] < 0:
            return False
        if p_dicc["cat"] <0 or p_dicc["cat"] >3:
            return False
        if p_dicc["excel"] <0 or p_dicc["excel"] >3:
            return False
        if p_dicc["titol"] <0 or p_dicc["titol"] >3:
            return False

        return True

    except ValueError:
        print("Error: Si us plau, introdueix números vàlids.")
        return False

**Interpretació:** aquesta funció transforma les dades del candidat en una puntuació numèrica aplicant la fórmula indicada a l'enunciat.

✔ `calcular_puntuacio(p_dicc)`

1. Rebre com a paràmetre el diccionari del candidat ja validat.
2. Multiplicar els anys d'experiència per `1.5`.
3. Sumar al resultat els punts de català.
4. Sumar els punts d'Excel.
5. Sumar els punts de titulació.
6. Guardar el resultat en la puntuació del candidat.
7. Retornar la puntuació calculada.

In [152]:
def calcular_puntuacio(p_dicc):

    return (p_dicc["exp"] * 1.5) + p_dicc["cat"] + p_dicc["excel"] + p_dicc["titol"]

**Interpretació:** aquesta funció rep una puntuació i decideix a quin dels tres grups de prioritat pertany el candidat.

✔ `classificar_candidat(p_puntuacio)`

1. Rebre com a paràmetre la puntuació del candidat.
2. Si la puntuació és igual o superior a 12, assignar la classificació `Prioritat Alta`.
3. Si no, però la puntuació és igual o superior a 8, assignar la classificació `Candidat adequat`.
4. Si no es compleix cap de les condicions anteriors, assignar la classificació `No prioritari`.
5. Retornar la classificació obtinguda.

In [31]:
def classificar_candidat(p_puntuacio):
    if p_puntuacio >= 12:
        classificacio = "Prioritat Alta"
    elif p_puntuacio >= 8:
        classificacio = "Candidat adequat"
    else:
        classificacio = "No prioritari"
    return classificacio

**Interpretació:** aquesta funció només s'encarrega de mostrar a cada candidat la puntuació que ha obtingut després del càlcul.

✔ `mostrar_individual(p_puntuacio_candidat)`

1. Rebre com a paràmetre la puntuació del candidat.
2. Mostrar en pantalla la puntuació individual del candidat.

In [32]:
def mostrar_individual(p_puntuacio_candidat):
    print(f"La teva puntuació és: {p_puntuacio_candidat}")

**Interpretació:** aquesta funció presenta en pantalla la informació necessària per a l'informe. En la versió final haurà de mostrar els candidats ja preparats i ordenats.

✔ `mostrar_informe(p_dicc)`

1. Rebre les dades del candidat que s'han de mostrar.
2. Accedir al nom del candidat.
3. Accedir al telèfon del candidat.
4. Accedir a la puntuació del candidat.
5. Mostrar en pantalla el nom, el telèfon i la puntuació amb salts de línia per facilitar-ne la lectura.

> **Nota:** quan es construeixi el programa complet amb els 10 candidats, l'informe final haurà de treballar amb tots els candidats i mostrar-los en l'ordre demanat per l'enunciat.

In [33]:
def mostrar_informe(p_llista_candidats):

    for candidat in p_llista_candidats:
        print(
        f"Nom: {candidat['nom']}\n"
        f"Telèfon: {candidat['telf']}\n"
        f"Puntuació: {candidat['puntuacio']}"
    )

**Interpretació:** aquesta és la funció que coordina tot el programa. No fa els càlculs directament, sinó que va cridant les altres funcions en l'ordre correcte fins a aconseguir 10 candidats vàlids i generar l'informe final.

🧠 **Algoritme principal**

✔ `main_seleccio()`

1. Crear una estructura per guardar els candidats vàlids.
2. Repetir el procés mentre encara no hi hagi 10 candidats vàlids.
3. Cridar `obtenir_dades()` per obtenir les dades d'un candidat.
4. Cridar `validar_dades()` per comprovar les dades introduïdes.
5. Si les dades són vàlides:
   - calcular la puntuació amb `calcular_puntuacio()`,
   - guardar la puntuació amb les dades del candidat,
   - classificar el candidat amb `classificar_candidat()`,
   - guardar la classificació amb les dades del candidat,
   - mostrar la puntuació amb `mostrar_individual()`,
   - guardar el candidat a l'estructura de candidats vàlids.
6. Si les dades no són vàlides, no comptar el candidat dins dels 10 registres vàlids.
7. Quan hi hagi exactament 10 candidats vàlids, deixar de demanar noves inscripcions.
8. Ordenar els candidats segons la prioritat indicada a l'enunciat i, en cas d'empat, segons la puntuació.
9. Mostrar l'informe final amb `mostrar_informe()`.

In [151]:
def main_seleccio():
    llista_candidats = []

    while len(llista_candidats) < 10:
        dicc_candidat = obtenir_dades()
        validacio = validar_dades(dicc_candidat)

        if validacio is True:
            dicc_candidat["puntuacio"] = calcular_puntuacio(dicc_candidat)
            dicc_candidat["classificacio"] = classificar_candidat(dicc_candidat["puntuacio"])
            mostrar_individual(dicc_candidat["puntuacio"])
            llista_candidats.append(dicc_candidat)

    llista_candidats.sort(key=lambda candidat: candidat["puntuacio"], reverse=True)
    mostrar_informe(llista_candidats)

### ✔ Prova automàtica del programa complet

**Interpretació:** aquesta és l'única cel·la de prova de l'Exercici 1 que executa el formulari. Permet fer **Run All** sense haver d'escriure manualment les dades dels candidats.

La llista `inputs_test` conté les respostes en el mateix ordre en què `obtenir_dades()` les demana: nom, telèfon, experiència, català, Excel i titulació.

1. Crear `inputs_test` amb totes les respostes de prova.
2. Crear un iterador amb `iter(inputs_test)`.
3. Guardar la funció `input` original.
4. Substituir temporalment `input()` perquè agafi automàticament el següent valor de la llista.
5. Executar `main_seleccio()`.
6. Restaurar l'`input` original amb `finally`.

**Idea clau:** les funcions anteriors només es defineixen; no s'executen individualment. D'aquesta manera, en fer **Run All**, no apareix cap quadre demanant nom, telèfon o altres dades.

In [35]:
inputs_test = [
    'Laura Serra',
    '608112233',
    '6',
    '3',
    '3',
    '3',
    'Clara Gómez',
    '655221199',
    '3',
    '3',
    '3',
    '2',
    'Sergio López',
    '644112211',
    '3',
    '2',
    '2',
    '2',
    'Candidat Error',
    '611000000',
    '5',
    '7',
    '3',
    '2',
    'Marta Ruiz',
    '699887766',
    '2',
    '3',
    '2',
    '1',
    'Marc Vidal',
    '612443322',
    '6',
    '3',
    '3',
    '3',
    'Júlia Romero',
    '677998877',
    '5',
    '3',
    '3',
    '2',
    'Pol Navarro',
    '699554433',
    '4',
    '3',
    '2',
    '2',
    'David Ferrer',
    '677665544',
    '2',
    '1',
    '1',
    '1',
    'Anna Paredes',
    '633221144',
    '1',
    '2',
    '1',
    '0',
    'Aníbal Paredes',
    '644272727',
    '1',
    '2',
    '1',
    '0',
    'Núria Casals',
    '600112200',
    '8',
    '2',
    '3',
    '3'
]

iterador = iter(inputs_test)

input_original = input
input = lambda *args: str(next(iterador))

try:
    main_seleccio()
finally:
    input = input_original

La teva puntuació és: 18.0
La teva puntuació és: 12.5
La teva puntuació és: 10.5
La teva puntuació és: 9.0
La teva puntuació és: 18.0
La teva puntuació és: 15.5
La teva puntuació és: 13.0
La teva puntuació és: 6.0
La teva puntuació és: 4.5
La teva puntuació és: 4.5
Nom: Laura Serra
Telèfon: 608112233
Puntuació: 18.0
Nom: Marc Vidal
Telèfon: 612443322
Puntuació: 18.0
Nom: Júlia Romero
Telèfon: 677998877
Puntuació: 15.5
Nom: Pol Navarro
Telèfon: 699554433
Puntuació: 13.0
Nom: Clara Gómez
Telèfon: 655221199
Puntuació: 12.5
Nom: Sergio López
Telèfon: 644112211
Puntuació: 10.5
Nom: Marta Ruiz
Telèfon: 699887766
Puntuació: 9.0
Nom: David Ferrer
Telèfon: 677665544
Puntuació: 6.0
Nom: Anna Paredes
Telèfon: 633221144
Puntuació: 4.5
Nom: Aníbal Paredes
Telèfon: 644272727
Puntuació: 4.5

## Exercici 2: Segmentació per risc de cistella de compra

Treballes com a analista de dades al departament de Màrqueting Digital. L'empresa vol millorar l'efectivitat de les campanyes de recuperació de cistellas de compra abandonats i necessita identificar quins clients tenen més risc d'abandonament, quin segment de comportament presenten i quin missatge publicitari és el més adequat per a cadascun.
Un cop processats els clients, has de ser capaç de respondre:

» 1. Quins clients s'han de contactar primer en una campanya de retargeting?
» 2. Quines diferències hi ha entre clients amb el mateix comportament però d'edats diferents? (Per exemple: un client jove que abandona la cistella de compra fa 24 h té el mateix risc que un de més edat?)
» 3. Quins clients presenten tan poc interès que no val la pena invertir-hi pressupost?
» 4. Quin client seria el més rendible de recuperar?
Interpretant el risc final i el segment.

## 🧠 Algoritme inicial

1. Crear una llista de diccionaris amb els 10 clients proporcionats a l'enunciat. Cada diccionari representarà un client i contindrà:
   - `id_client`
   - `nom`
   - `edat`
   - `grup_edat`
   - `codi_comportament`

2. Crear la funció `obtenir_segment_i_factor()`:
   - Crear un diccionari de diccionaris que relacioni cada `codi_comportament` amb:
     - `segment`
     - `missatge`
     - `factor_codi`
   - Retornar aquest diccionari.

3. Crear la funció `obtenir_factor_edat()`:
   - Crear un diccionari que relacioni cada `grup_edat` amb el seu `factor_edat`.
   - Retornar aquest diccionari.

4. Crear la funció `calcular_risc(p_clients, p_dicc_codi_comp, p_dicc_edat)`:
   - Rebre la llista de clients.
   - Rebre el diccionari de codis de comportament.
   - Rebre el diccionari de factors d'edat.
   - Recórrer la llista de clients amb un bucle.
   - Per cada client:
     - consultar el seu `codi_comportament`
     - obtenir el `segment` corresponent
     - obtenir el `missatge` corresponent
     - obtenir el `factor_codi` corresponent
     - consultar el seu `grup_edat`
     - obtenir el `factor_edat` corresponent
     - calcular `risc_final = factor_codi * factor_edat`
     - afegir al diccionari del client les noves claus:
       - `segment`
       - `missatge`
       - `factor_codi`
       - `factor_edat`
       - `risc_final`
   - Retornar la llista de clients actualitzada.

5. Convertir la llista de diccionaris actualitzada en un DataFrame.

6. Crear la funció `mostrar_dataframe()` per mostrar el DataFrame final amb totes les dades dels clients.

7. Analitzar les dades finals per respondre les preguntes del departament de Màrqueting Digital.

8. Crear la funció `mostrar_respostes()` per mostrar les respostes obtingudes.

9. Crear la funció `main_marketing(p_clients)` que orquestri el procés complet:
   - Rebre la llista de clients.
   - Cridar `processar_clients(p_clients)` per obtenir la llista de clients ja completada amb el segment, missatge, factors i risc final.
   - Guardar el resultat retornat com a `clients_final`.
   - Cridar `mostrar_dataframe(clients_final)` per convertir i mostrar les dades en format DataFrame.
   - Guardar el DataFrame retornat.
   - Cridar `mostrar_respostes(df_clients)` per analitzar les dades i mostrar les respostes de màrqueting.

🧩 **Desgranant el problema: naixement de les funcions**

### ✔ Preparació de les dades: `clients`

**Interpretació:** aquesta estructura conté les dades inicials dels 10 clients. És una **llista de diccionaris**: cada element de la llista és un client i cada client guarda les seves dades mitjançant claus i valors.

1. Crear una llista anomenada `clients`.
2. Guardar dins la llista un diccionari per cada client.
3. Cada diccionari ha de contenir:
   - `id_client`
   - `nom`
   - `edat`
   - `grup_edat`
   - `codi_comportament`
4. Aquesta llista serà la base sobre la qual treballaran les funcions següents.

In [36]:
clients = [ 
    {"id_client": 1, "nom": "Laura Serra", "edat": 23, "grup_edat": "18-25", "codi_comportament": 4}, 
    {"id_client": 2, "nom": "Marc Vidal", "edat": 35, "grup_edat": "26-40", "codi_comportament": 3}, 
    {"id_client": 3, "nom": "Ana López", "edat": 29, "grup_edat": "26-40", "codi_comportament": 2}, 
    {"id_client": 4, "nom": "Joan Riera", "edat": 19, "grup_edat": "18-25", "codi_comportament": 2}, 
    {"id_client": 5, "nom": "Mónica Pérez", "edat": 47, "grup_edat": "41-60", "codi_comportament": 4}, 
    {"id_client": 6, "nom": "Luis García", "edat": 52, "grup_edat": "41-60", "codi_comportament": 1}, 
    {"id_client": 7, "nom": "Pilar Sánchez", "edat": 61, "grup_edat": "60+", "codi_comportament": 3}, 
    {"id_client": 8, "nom": "Eva Martín", "edat": 38, "grup_edat": "26-40", "codi_comportament": 0}, 
    {"id_client": 9, "nom": "Diego Romero", "edat": 24, "grup_edat": "18-25", "codi_comportament": 1}, 
    {"id_client": 10, "nom": "Núria Costa", "edat": 33, "grup_edat": "26-40", "codi_comportament": 4} 
] 

print(clients)

[{'id_client': 1, 'nom': 'Laura Serra', 'edat': 23, 'grup_edat': '18-25', 'codi_comportament': 4}, {'id_client': 2, 'nom': 'Marc Vidal', 'edat': 35, 'grup_edat': '26-40', 'codi_comportament': 3}, {'id_client': 3, 'nom': 'Ana López', 'edat': 29, 'grup_edat': '26-40', 'codi_comportament': 2}, {'id_client': 4, 'nom': 'Joan Riera', 'edat': 19, 'grup_edat': '18-25', 'codi_comportament': 2}, {'id_client': 5, 'nom': 'Mónica Pérez', 'edat': 47, 'grup_edat': '41-60', 'codi_comportament': 4}, {'id_client': 6, 'nom': 'Luis García', 'edat': 52, 'grup_edat': '41-60', 'codi_comportament': 1}, {'id_client': 7, 'nom': 'Pilar Sánchez', 'edat': 61, 'grup_edat': '60+', 'codi_comportament': 3}, {'id_client': 8, 'nom': 'Eva Martín', 'edat': 38, 'grup_edat': '26-40', 'codi_comportament': 0}, {'id_client': 9, 'nom': 'Diego Romero', 'edat': 24, 'grup_edat': '18-25', 'codi_comportament': 1}, {'id_client': 10, 'nom': 'Núria Costa', 'edat': 33, 'grup_edat': '26-40', 'codi_comportament': 4}]

### ✔ `obtenir_segment_i_factor()`

**Interpretació:** aquesta funció crea una taula de consulta. A partir d'un `codi_comportament`, permet saber quin `segment`, quin `missatge` i quin `factor_codi` li correspon al client, sense utilitzar `if/elif/else`.

1. Crear un diccionari de diccionaris.
2. Utilitzar els codis `0`, `1`, `2`, `3` i `4` com a claus principals.
3. Per cada codi, guardar un diccionari interior amb:
   - `segment`
   - `missatge`
   - `factor_codi`
4. Retornar el diccionari complet.

**Idea clau:** `diccionari[codi]` retorna el diccionari interior d'aquell codi, i després es pot accedir a una dada concreta amb una segona clau, per exemple `["factor_codi"]`.

In [37]:
def obtenir_segment_i_factor():

    dicc_factor_codi_comportament = {
        0: {
            "segment": "Navega però no afegeix productes",
            "missatge": "Descobreix els productes seleccionats per a tu",
            "factor_codi": 0.10
        },
        1: {
            "segment": "Afegeix productes però no arriba al checkout",
            "missatge": "Els teus productes t'estan esperant",
            "factor_codi": 0.25
        },
        2: {
            "segment": "Arriba al checkout però no paga",
            "missatge": "Completa la teva compra",
            "factor_codi": 0.50
        },
        3: {
            "segment": "Cistella de compra abandonada fa menys de 24 h",
            "missatge": "Has deixat alguna cosa a la cistella. Finalitza la teva compra",
            "factor_codi": 0.75
        },
        4: {
            "segment": "Cistella de compra abandonada fa més de 24 h",
            "missatge": "Encara t'interessa? Recupera la teva cistella",
            "factor_codi": 0.90
        }
    }
    return dicc_factor_codi_comportament

### ✔ `obtenir_factor_edat()`

**Interpretació:** aquesta funció crea una segona taula de consulta que relaciona cada grup d'edat amb el factor que li correspon.

1. Crear un diccionari.
2. Utilitzar cada `grup_edat` com a clau.
3. Guardar com a valor el `factor_edat` corresponent.
4. Retornar el diccionari.

**Idea clau:** si un client té `"grup_edat": "18-25"`, consultar `dicc_edat["18-25"]` retorna el factor `1.20`.

In [38]:
def obtenir_factor_edat():

    dicc_factor_edat = {
        "18-25": 1.20,
        "26-40": 1.00,
        "41-60": 0.85,
        "60+": 0.70
    }
    return dicc_factor_edat

### ✔ `calcular_risc(p_clients, p_dicc_codi_comp, p_dicc_edat)`

**Interpretació:** aquesta funció recorre tots els clients i enriqueix cada diccionari amb la informació que li correspon segons el seu comportament i la seva edat. Finalment calcula el risc de cada client.

1. Rebre:
   - la llista de clients,
   - el diccionari de codis de comportament,
   - el diccionari de factors d'edat.
2. Recórrer la llista amb `for client in p_clients`.
3. A cada volta, `client` representa **un diccionari individual** de la llista.
4. Consultar `client["codi_comportament"]` per saber quin codi té aquell client.
5. Utilitzar aquest codi per consultar `p_dicc_codi_comp` i obtenir:
   - el `segment`,
   - el `missatge`,
   - el `factor_codi`.
6. Consultar `client["grup_edat"]` i utilitzar-lo per obtenir el `factor_edat` des de `p_dicc_edat`.
7. Afegir aquestes dades com a noves claus dins del diccionari del client.
8. Calcular:
   - `risc_final = factor_codi * factor_edat`
9. Guardar `risc_final` dins del diccionari del client.
10. Repetir el procés per tots els clients.
11. Retornar la llista completa ja actualitzada.

**Idea clau:** el `for` permet que `client["codi_comportament"]` faci referència al codi del client que s'està processant en aquella volta.

In [39]:
def calcular_risc(p_clients, p_dicc_codi_comp, p_dicc_edat):

    for client in p_clients:
        client["segment"] = p_dicc_codi_comp[client["codi_comportament"]]["segment"]
        client["missatge"] = p_dicc_codi_comp[client["codi_comportament"]]["missatge"]
        client["factor_codi"] = p_dicc_codi_comp[client["codi_comportament"]]["factor_codi"]
        client["factor_edat"] = p_dicc_edat[client["grup_edat"]]
        client["risc_final"] = client["factor_codi"] * client["factor_edat"]

    return p_clients

### ✔ `processar_clients(p_clients)`

**Interpretació:** aquesta funció coordina les funcions necessàries per completar les dades dels clients. Obté els diccionaris de consulta i els passa, juntament amb la llista de clients, a `calcular_risc()`.

1. Rebre la llista de clients mitjançant `p_clients`.
2. Cridar `obtenir_segment_i_factor()` i guardar el diccionari retornat a `dicc_codis`.
3. Cridar `obtenir_factor_edat()` i guardar el diccionari retornat a `dicc_edat`.
4. Cridar `calcular_risc()` passant:
   - `p_clients`,
   - `dicc_codis`,
   - `dicc_edat`.
5. Guardar la llista actualitzada a `clients_final`.
6. Retornar `clients_final`.

**Idea clau:** `processar_clients()` concentra els passos interns de preparació. Així `main_marketing()` només necessita demanar que es processin els clients i rebre el resultat final.

In [40]:
def processar_clients(p_clients):
    dicc_codis = obtenir_segment_i_factor()
    dicc_edat = obtenir_factor_edat()
    clients_final = calcular_risc(p_clients, dicc_codis, dicc_edat)
    return clients_final

### ✔ `mostrar_dataframe(p_clients)`

**Interpretació:** aquesta funció transforma la llista de diccionaris ja processada en una taula de Pandas, la mostra de forma visual i retorna el DataFrame perquè es pugui continuar analitzant.

1. Rebre la llista de clients processats.
2. Convertir-la en un DataFrame mitjançant `pd.DataFrame()`.
3. Guardar el DataFrame a `df_clients`.
4. Mostrar el DataFrame amb `display()`.
5. Retornar `df_clients` perquè altres funcions el puguin utilitzar.

**Idea clau:** cada diccionari de la llista es converteix en una fila i cada clau es converteix en una columna.

In [41]:
def mostrar_dataframe(p_clients):
    df_clients = pd.DataFrame(p_clients)
    display(df_clients)
    return df_clients

### Preguntes del Departament de Màrqueting Digital:

1. Quins clients s'han de contactar primer en una campanya de retargeting?
2. Quines diferències hi ha entre clients amb el mateix comportament però d'edats diferents? (Per exemple: un client jove que abandona la cistella de compra fa 24 h té el mateix risc que un de més edat?)
3. Quins clients presenten tan poc interès que no val la pena invertir-hi pressupost?
4. Quin client seria el més rendible de recuperar?

Interpretant el risc final i el segment.

### ✔ `mostrar_respostes(p_df_clients)`

**Interpretació:** aquesta funció rep i analitza el DataFrame final per respondre les quatre preguntes del departament de Màrqueting Digital.

1. **Pregunta 1:** ordenar els clients per `risc_final` de major a menor per veure quins s'han de contactar primer.
2. Mostrar només les dades necessàries per interpretar la prioritat:
   - `nom`
   - `segment`
   - `risc_final`
3. **Pregunta 2:** comparar clients amb el mateix `codi_comportament` però amb grups d'edat diferents.
4. Mostrar:
   - `nom`
   - `codi_comportament`
   - `grup_edat`
   - `factor_edat`
   - `risc_final`
5. **Pregunta 3:** identificar els clients amb un `risc_final` baix segons el criteri utilitzat a l'exercici i mostrar-los.
6. **Pregunta 4:** ordenar per `risc_final`, seleccionar el primer client i extreure'n el nom.
7. Mostrar les respostes de forma llegible.

**Idea clau:** aquí ja no es calculen els factors; s'analitzen les dades que s'han creat anteriorment.

In [42]:
def mostrar_respostes(p_df_clients):

    pregunta_1 = p_df_clients.sort_values("risc_final", ascending=False)
    pregunta_1 = pregunta_1[["nom", "segment", "risc_final"]]
    print("1: Ordre de clients que s'han de contactar:")
    display(pregunta_1)

    pregunta_2 = p_df_clients[["nom", "codi_comportament", "grup_edat", "factor_edat", "risc_final"]]
    pregunta_2 = pregunta_2.sort_values("codi_comportament")
    print("2: A la següent taula es poden apreciar les diferències entre clients amb el mateix comportament però de grups d'edat diferents:")
    display(pregunta_2)

    pregunta_3 = p_df_clients[["nom", "codi_comportament", "grup_edat", "risc_final"]]
    pregunta_3 = pregunta_3.sort_values("risc_final", ascending=False)
    pregunta_3 = pregunta_3[pregunta_3["risc_final"] <= 0.50]
    print("3: Clients amb poc interès, els quals no val la pena invertir-hi pressupost:")
    display(pregunta_3)

    pregunta_4 = p_df_clients.sort_values("risc_final", ascending=False).head(1)
    nom_client = pregunta_4["nom"].iloc[0]
    print(f"4: El client més rendible de recuperar és: {nom_client}")

## 🧠 Algoritme principal

### ✔ `main_marketing(p_clients)`

**Interpretació:** aquesta és la funció principal que orquestra tot el programa. Rep una llista de clients i va passant els resultats d'una funció a la següent fins a obtenir i analitzar el DataFrame final.

1. Rebre la llista de clients mitjançant el paràmetre `p_clients`.
2. Cridar `processar_clients(p_clients)` i guardar la llista de clients ja completada amb `segment`, `missatge`, `factor_codi`, `factor_edat` i `risc_final`.
3. Cridar `mostrar_dataframe()` amb els clients processats.
4. Guardar el DataFrame retornat.
5. Passar el DataFrame a `mostrar_respostes()` perquè analitzi i mostri les quatre respostes de màrqueting.

**Flux mental:**

`p_clients` → `processar_clients()` → `clients_final` → `mostrar_dataframe()` → `df_clients` → `mostrar_respostes()`

In [43]:
def main_marketing(p_clients):
    clients_final = processar_clients(p_clients)
    df_clients = mostrar_dataframe(clients_final)
    mostrar_respostes(df_clients)

main_marketing(clients)

,id_client,nom,edat,grup_edat,codi_comportament,segment,missatge,factor_codi,factor_edat,risc_final
0,1,Laura Serra,23,18-25,4,Cistella de compra abandonada fa més de 24 h,Encara t'interessa? Recupera la teva cistella,0.90,1.20,1.0800
1,2,Marc Vidal,35,26-40,3,Cistella de compra abandonada fa menys de 24 h,Has deixat alguna cosa a la cistella. Finalitz...,0.75,1.00,0.7500
2,3,Ana López,29,26-40,2,Arriba al checkout però no paga,Completa la teva compra,0.50,1.00,0.5000
3,4,Joan Riera,19,18-25,2,Arriba al checkout però no paga,Completa la teva compra,0.50,1.20,0.6000
4,5,Mónica Pérez,47,41-60,4,Cistella de compra abandonada fa més de 24 h,Encara t'interessa? Recupera la teva cistella,0.90,0.85,0.7650
5,6,Luis García,52,41-60,1,Afegeix productes però no arriba al checkout,Els teus productes t'estan esperant,0.25,0.85,0.2125
6,7,Pilar Sánchez,61,60+,3,Cistella de compra abandonada fa menys de 24 h,Has deixat alguna cosa a la cistella. Finalitz...,0.75,0.70,0.5250
7,8,Eva Martín,38,26-40,0,Navega però no afegeix productes,Descobreix els productes seleccionats per a tu,0.10,1.00,0.1000
8,9,Diego Romero,24,18-25,1,Afegeix productes però no arriba al checkout,Els teus productes t'estan esperant,0.25,1.20,0.3000
9,10,Núria Costa,33,26-40,4,Cistella de compra abandonada fa més de 24 h,Encara t'interessa? Recupera la teva cistella,0.90,1.00,0.9000

1: Ordre de clients que s'han de contactar:

             nom                                         segment  risc_final
0    Laura Serra    Cistella de compra abandonada fa més de 24 h      1.0800
9    Núria Costa    Cistella de compra abandonada fa més de 24 h      0.9000
4   Mónica Pérez    Cistella de compra abandonada fa més de 24 h      0.7650
1     Marc Vidal  Cistella de compra abandonada fa menys de 24 h      0.7500
3     Joan Riera                 Arriba al checkout però no paga      0.6000
6  Pilar Sánchez  Cistella de compra abandonada fa menys de 24 h      0.5250
2      Ana López                 Arriba al checkout però no paga      0.5000
8   Diego Romero    Afegeix productes però no arriba al checkout      0.3000
5    Luis García    Afegeix productes però no arriba al checkout      0.2125
7     Eva Martín                Navega però no afegeix productes      0.1000

2: A la següent taula es poden apreciar les diferències entre clients amb el mateix comportament però de grups d'edat diferents:

             nom  codi_comportament grup_edat  factor_edat  risc_final
7     Eva Martín                  0     26-40         1.00      0.1000
5    Luis García                  1     41-60         0.85      0.2125
8   Diego Romero                  1     18-25         1.20      0.3000
3     Joan Riera                  2     18-25         1.20      0.6000
2      Ana López                  2     26-40         1.00      0.5000
6  Pilar Sánchez                  3       60+         0.70      0.5250
1     Marc Vidal                  3     26-40         1.00      0.7500
0    Laura Serra                  4     18-25         1.20      1.0800
4   Mónica Pérez                  4     41-60         0.85      0.7650
9    Núria Costa                  4     26-40         1.00      0.9000

3: Clients amb poc interès, els quals no val la pena invertir-hi pressupost:

            nom  codi_comportament grup_edat  risc_final
2     Ana López                  2     26-40      0.5000
8  Diego Romero                  1     18-25      0.3000
5   Luis García                  1     41-60      0.2125
7    Eva Martín                  0     26-40      0.1000

4: El client més rendible de recuperar és: Laura Serra

# NIVELL 2

## Exercici 1: Gestió de risc i priorització de pacients
Treballes com a analista de dades en un centre mèdic especialitzat. Diversos pacients han enviat els seus símptomes a través d'un formulari online, però les dades arriben en un format desordenat i poc estructurat, i l'equip mèdic necessita que els organitzis per poder prioritzar l'ordre d'atenció segons la gravetat. 
L'objectiu és transformar aquestes dades en informació útil per als metges. A partir dels registres en brut, has de:
» Convertir cada string en una estructura neta (diccionari o similar).
» Separar i normalitzar la llista de símptomes:
minúscules
eliminar espais
dividir correctament per comes
» Assignar un risc a cada símptoma utilitzant el diccionari nivells_risc.
» Calcular el risc total de cada pacient sumant els valors.
» Ordenar els pacients de major a menor risc per determinar la prioritat d'atenció.
✅ Resultat esperat: Un DataFrame o un diccionari amb: nom, edat, símptomes normalitzats i risc_total.
I un apartat final amb els pacients ordenats per prioritat (més risc → primer).

### 🧠 Algoritme inicial

1. Crear una llista amb les dades dels 5 pacients rebudes mitjançant el formulari online.

2. Crear la funció `netejar_dades()` per netejar i separar les dades de cada pacient:
   - Recórrer la llista de pacients.
   - Convertir cada registre a minúscules amb `.lower()`.
   - Separar `nom`, `edat` i `símptomes` utilitzant `|` com a separador.
   - Separar els diferents símptomes utilitzant `,` com a separador.
   - Recórrer la llista de símptomes de cada pacient.
   - Eliminar els espais sobrants al principi i al final amb `.strip()`.
   - Substituir els espais interns dels símptomes per `_` amb `.replace(" ", "_")`, per adaptar-los al format del diccionari `nivells_risc`.
   - Guardar els símptomes normalitzats en una llista.
   - Guardar cada pacient net dins de la llista de pacients nets.
   - Retornar la llista de pacients nets.

3. Crear la funció `validar_dades()` per convertir i validar les dades:
   - Rebre la llista de pacients nets.
   - Recórrer cada pacient.
   - Convertir l'edat de `string` a `int`.
   - Comprovar que les dades siguin vàlides.
   - Retornar `True` si les dades són vàlides i `False` si es produeix un error en la conversió.

4. Crear una funció per transformar les dades validades en una llista de diccionaris.
   - Recórrer la llista de pacients.
   - Crear un diccionari per cada pacient amb:
      - `nom`
      - `edat`
      - `simptomes`
   - Guardar cada diccionari en una llista.
   - Retornar la llista de diccionaris.

5. Crear el diccionari `nivells_risc` amb els nivells de risc proporcionats pel departament mèdic.

6. Crear una funció per calcular el risc de cada pacient:
   - Recórrer la llista de diccionaris dels pacients.
   - Per cada pacient, recórrer la seva llista de símptomes.
   - Consultar al diccionari `nivells_risc` el nivell corresponent a cada símptoma.
   - Sumar els nivells de risc dels símptomes de cada pacient.
   - Afegir una nova clau `risc_total` al diccionari de cada pacient amb el resultat de la suma.
   - Retornar la llista de pacients actualitzada.

7. Crear una funció per convertir la llista de diccionaris en un DataFrame amb les columnes:
   - `nom`
   - `edat`
   - `simptomes`
   - `risc_total`

8. Crear una funció per ordenar els pacients segons `risc_total`, de major a menor, per establir la prioritat d'atenció.

9. Crear una funció per mostrar el DataFrame final ordenat.

10. Crear una funció principal que orquestri tot el procés:
   - Cridar `netejar_dades()`.
   - Passar les dades netes a `validar_dades()`.
   - Transformar els pacients validats en una llista de diccionaris.
   - Obtenir el diccionari `nivells_risc`.
   - Calcular el `risc_total` de cada pacient.
   - Convertir la llista de diccionaris a DataFrame.
   - Ordenar els pacients de major a menor risc.
   - Mostrar el DataFrame final.

### ✔ Preparació de les dades: `pacients`

**Interpretació:** aquesta llista conté els registres en brut rebuts des del formulari. Cada pacient està guardat inicialment com un únic `string`, amb les dades separades pel caràcter `|`.

1. Crear la llista `pacients`.
2. Guardar un registre de text per cada pacient.
3. Mantenir el format original rebut, encara que contingui majúscules, minúscules i espais irregulars.
4. Utilitzar aquesta llista com a punt de partida del procés de neteja.

**Idea clau:** aquestes són les dades en brut; encara no estan preparades per calcular el risc.

In [44]:
pacients = [ 
    "Maria|45|tos, Fiebre Alta, dolor_pecho", 
    "Luis|33|dolor_cabeza,faTiga", 
    "Sara|67|fiebre alta, dificultad RESPIRAR, tos", 
    "Jordi|52|fatiga , tos", 
    "Anna|29|fiebre alta,dolor_cabeza" 
]

### ✔ `netejar_dades(p_pacients)`

**Interpretació:** aquesta funció neteja els registres en brut i normalitza els símptomes perquè tinguin el mateix format que les claus del diccionari `nivells_risc`.

1. Rebre la llista de pacients.
2. Crear una llista buida `pacients_nets`.
3. Recórrer cada registre amb un `for`.
4. Convertir el text a minúscules amb `.lower()`.
5. Separar nom, edat i símptomes amb `.split("|")`.
6. Separar els símptomes amb `.split(",")`.
7. Eliminar espais sobrants amb `.strip()`.
8. Substituir espais interns per `_`.
9. Guardar la llista de símptomes normalitzats dins del pacient.
10. Afegir el pacient net a `pacients_nets`.
11. Retornar la llista completa.

**Idea clau:** la normalització permet que, per exemple, `Fiebre Alta` es converteixi en `fiebre_alta`.

In [45]:
def netejar_dades(p_pacients):

    pacients_nets = []

    for pacient in p_pacients:

        pacient_net = pacient.lower()
        pacient_net = pacient_net.split("|")
        simptomes = pacient_net[2].split(",")
        simptomes_nets = []

        for simptoma in simptomes:
            simptoma = simptoma.strip()
            simptoma = simptoma.replace(" ", "_")
            simptomes_nets.append(simptoma)

        pacient_net[2] = simptomes_nets
        pacients_nets.append(pacient_net)

    return pacients_nets

dades_netes = netejar_dades(pacients)
print(dades_netes)

[['maria', '45', ['tos', 'fiebre_alta', 'dolor_pecho']], ['luis', '33', ['dolor_cabeza', 'fatiga']], ['sara', '67', ['fiebre_alta', 'dificultad_respirar', 'tos']], ['jordi', '52', ['fatiga', 'tos']], ['anna', '29', ['fiebre_alta', 'dolor_cabeza']]]

### ✔ `validar_dades(p_pacients)`

**Interpretació:** aquesta funció comprova que l'edat dels pacients es pugui convertir correctament a número abans de continuar amb el procés.

1. Rebre la llista de pacients nets.
2. Recórrer cada pacient.
3. Intentar convertir l'edat de `string` a `int`.
4. Si totes les conversions funcionen, retornar `True`.
5. Si alguna conversió genera un `ValueError`, retornar `False`.

**Idea clau:** la funció valida les dades; el `main` decideix si continua o no segons el resultat.

In [46]:
def validar_dades(p_pacients):

    try:
        for pacient in p_pacients:
            pacient[1] = int(pacient[1])

        return True

    except ValueError:
        return False

dades_validades = validar_dades(dades_netes)
print(dades_netes)

[['maria', 45, ['tos', 'fiebre_alta', 'dolor_pecho']], ['luis', 33, ['dolor_cabeza', 'fatiga']], ['sara', 67, ['fiebre_alta', 'dificultad_respirar', 'tos']], ['jordi', 52, ['fatiga', 'tos']], ['anna', 29, ['fiebre_alta', 'dolor_cabeza']]]

### ✔ `crear_diccionaris(p_pacients)`

**Interpretació:** aquesta funció transforma cada pacient, que fins ara és una llista, en un diccionari amb claus descriptives.

1. Rebre la llista de pacients nets i validats.
2. Crear una llista buida `pacients_dicc`.
3. Recórrer cada pacient.
4. Crear un diccionari amb:
   - `nom`
   - `edat`
   - `simptomes`
5. Afegir cada diccionari a `pacients_dicc`.
6. Retornar la llista de diccionaris.

**Idea clau:** passem d'accedir a les dades per posició (`pacient[0]`) a fer-ho per una clau clara (`pacient["nom"]`).

In [47]:
def crear_diccionaris(p_pacients):

    pacients_dicc = []

    for pacient in p_pacients:

        dicc_pacient = {
            "nom": pacient[0],
            "edat": pacient[1],
            "simptomes": pacient[2]
        }

        pacients_dicc.append(dicc_pacient)

    return pacients_dicc

dicc_pacients = crear_diccionaris(dades_netes)
print(dicc_pacients)

[{'nom': 'maria', 'edat': 45, 'simptomes': ['tos', 'fiebre_alta', 'dolor_pecho']}, {'nom': 'luis', 'edat': 33, 'simptomes': ['dolor_cabeza', 'fatiga']}, {'nom': 'sara', 'edat': 67, 'simptomes': ['fiebre_alta', 'dificultad_respirar', 'tos']}, {'nom': 'jordi', 'edat': 52, 'simptomes': ['fatiga', 'tos']}, {'nom': 'anna', 'edat': 29, 'simptomes': ['fiebre_alta', 'dolor_cabeza']}]

### ✔ Diccionari `nivells_risc`

**Interpretació:** aquest diccionari funciona com una taula de consulta proporcionada pel departament mèdic. Relaciona cada símptoma normalitzat amb el seu nivell de risc.

- `fiebre_alta` → 3
- `dificultad_respirar` → 5
- `dolor_pecho` → 4
- `tos` → 1
- `fatiga` → 1
- `dolor_cabeza` → 1

**Idea clau:** com que els símptomes s'han normalitzat prèviament, es poden utilitzar directament com a claus del diccionari.

In [48]:
nivells_risc = { 
    "fiebre_alta": 3, 
    "dificultad_respirar": 5, 
    "dolor_pecho": 4, 
    "tos": 1, 
    "fatiga": 1, 
    "dolor_cabeza": 1 
}

### ✔ `calcular_risc_pacients(p_nivells_risc, p_pacients)`

**Interpretació:** aquesta funció calcula el risc total de cada pacient a partir dels símptomes normalitzats i del diccionari `nivells_risc`.

1. Rebre:
   - el diccionari amb els nivells de risc,
   - la llista de diccionaris dels pacients.
2. Recórrer cada pacient.
3. Inicialitzar `risc_total` a `0` per a cada pacient.
4. Recórrer la llista de `simptomes` del pacient.
5. Consultar al diccionari `p_nivells_risc` el valor de risc corresponent a cada símptoma.
6. Sumar cada valor a `risc_total`.
7. Afegir la nova clau `risc_total` al diccionari del pacient.
8. Retornar la llista de pacients actualitzada.

**Idea clau:** cada símptoma ja està normalitzat amb el mateix format que les claus de `nivells_risc`, per això es pot consultar directament el seu valor.

In [49]:
def calcular_risc_pacients(p_nivells_risc, p_pacients):

    for pacient in p_pacients:
        risc_total = 0

        for simptoma in pacient["simptomes"]:
            simptoma = p_nivells_risc[simptoma]
            risc_total = risc_total + simptoma

        pacient["risc_total"] = risc_total

    return p_pacients

dicc_pacients_final = calcular_risc_pacients(nivells_risc, dicc_pacients)
print(dicc_pacients_final)

[{'nom': 'maria', 'edat': 45, 'simptomes': ['tos', 'fiebre_alta', 'dolor_pecho'], 'risc_total': 8}, {'nom': 'luis', 'edat': 33, 'simptomes': ['dolor_cabeza', 'fatiga'], 'risc_total': 2}, {'nom': 'sara', 'edat': 67, 'simptomes': ['fiebre_alta', 'dificultad_respirar', 'tos'], 'risc_total': 9}, {'nom': 'jordi', 'edat': 52, 'simptomes': ['fatiga', 'tos'], 'risc_total': 2}, {'nom': 'anna', 'edat': 29, 'simptomes': ['fiebre_alta', 'dolor_cabeza'], 'risc_total': 4}]

### ✔ `crear_dataframe(p_pacients)`

**Interpretació:** aquesta funció transforma la llista de diccionaris dels pacients en un DataFrame de Pandas perquè es pugui ordenar i presentar en format de taula.

1. Rebre la llista de pacients ja processats.
2. Convertir-la en un DataFrame amb `pd.DataFrame()`.
3. Retornar el DataFrame.

**Idea clau:** aquesta funció només converteix les dades; no les mostra. Així podem ordenar primer el DataFrame i mostrar-lo una sola vegada al final.

In [57]:
def crear_dataframe(p_llista):
    df = pd.DataFrame(p_llista)
    return df

### ✔ `ordenar_df(p_df, p_columnes, p_ascendent=False)`

**Interpretació:** aquesta funció ordena qualsevol DataFrame segons una o diverses columnes i permet indicar si l'ordenació ha de ser ascendent o descendent.

1. Rebre:
   - `p_df`: el DataFrame que es vol ordenar.
   - `p_columnes`: una columna o una llista de columnes per les quals es vol ordenar.
   - `p_ascendent`: indica el sentit de l'ordenació (`True` ascendent / `False` descendent).

2. Utilitzar `sort_values()` per ordenar el DataFrame.

3. Passar `p_columnes` al paràmetre `by`.

4. Passar `p_ascendent` al paràmetre `ascending`.

5. Retornar el DataFrame ordenat.

**Idea clau:** les columnes i el sentit de l'ordenació es passen com a paràmetres, per tant la funció no està lligada a un DataFrame ni a unes columnes concretes i es pot reutilitzar en diferents exercicis.

In [62]:
def ordenar_df(p_df, p_columnes, p_ascendent=False):
    df_ordenat = p_df.sort_values(
        by=p_columnes,
        ascending=p_ascendent
    )
    return df_ordenat

## 🧠 Algoritme principal

### ✔ `main_pacients()`

**Interpretació:** aquesta és la funció principal que orquestra tot el procés. Va passant el resultat d'una funció a la següent fins a obtenir el DataFrame final ordenat per prioritat.

1. Cridar `netejar_dades(pacients)` i guardar les dades netes.
2. Validar les dades amb `validar_dades(dades_netes)`.
3. Si les dades són vàlides:
   - transformar-les en una llista de diccionaris amb `crear_diccionaris()`,
   - calcular el risc total amb `calcular_risc_pacients()`,
   - convertir el resultat a DataFrame amb `crear_dataframe()`,
   - ordenar el DataFrame de major a menor risc amb `ordenar_df()`,
   - mostrar una sola vegada el DataFrame final ja ordenat.
4. Retornar el DataFrame ordenat perquè es pugui reutilitzar posteriorment.

**Flux mental:**

`pacients` → `netejar_dades()` → `validar_dades()` → `crear_diccionaris()` → `calcular_risc_pacients()` → `crear_dataframe()` → `ordenar_df()` → `display()`

**Idea clau:** el `main` coordina el procés, mentre que cada funció s'encarrega d'una tasca concreta.

In [63]:
def main_pacients():
    dades_netes = netejar_dades(pacients)

    if validar_dades(dades_netes):
        dicc_pacients = crear_diccionaris(dades_netes)
        dicc_pacients_final = calcular_risc_pacients(nivells_risc, dicc_pacients)
        df_pacients = crear_dataframe(dicc_pacients_final)
        df_pacients_ordenat = ordenar_df(df_pacients, "risc_total", False)

        display(df_pacients_ordenat)
        return df_pacients_ordenat

df_pacients_final = main_pacients()

     nom  edat                                simptomes  risc_total
2   sara    67  [fiebre_alta, dificultad_respirar, tos]           9
0  maria    45          [tos, fiebre_alta, dolor_pecho]           8
4   anna    29              [fiebre_alta, dolor_cabeza]           4
1   luis    33                   [dolor_cabeza, fatiga]           2
3  jordi    52                            [fatiga, tos]           2

## Exercici 2: Classificació de clients de segurs

Treballes com a analista de dades en una companyia asseguradora.
L'empresa vol calcular el risc dels clients, el preu estimat de la pòlissa i la probabilitat de frau, utilitzant un codi de comportament que ha estat generat per un model intern.
🎯 Objectius:
1. Classificar cada client utilitzant nivells_seguro (sense if/elif).
2. Afegir: La categoria, El preu base, La probabilitat de frau
3. Calcular el preu final de la pòlissa amb la fórmula donada.
4. Crear un DataFrame o diccionari amb la informació final.
5. Ordenar els clients: Per probabilitat de frau (descendent), Per preu final.

### 🧠 Algoritme inicial:

1. Crear la llista de diccionaris `clients2` amb les dades proporcionades per la companyia asseguradora.

2. Crear el diccionari de diccionaris `nivells_seguro` amb les categories del sistema proporcionades per la companyia.

3. Crear una funció per classificar cada client utilitzant `nivells_seguro` (sense `if/elif`). Afegir al diccionari de cada client de la llista `clients2`:

    - La categoria.
    - El preu base.
    - La probabilitat de frau.

4. Crear una funció per calcular el preu final de cada client amb la fórmula:

    `preu_final = preu_base * (1 + edat / 100)`

    Afegir la clau `preu_final` al diccionari de cada client.

5. Reutilitzar la funció `crear_dataframe()` de l'exercici anterior per convertir la llista de diccionaris en un DataFrame.

6. Reutilitzar la funció generalitzada `ordenar_df()` de l'exercici anterior per ordenar el DataFrame segons la columna necessària:

    - Per `probabilitat_frau` de major a menor.
    - Per `preu_final` de major a menor.

7. Mostrar el DataFrame amb les següents columnes:

    - Nom
    - Edat
    - Categoria
    - Preu_base
    - Preu_final
    - Probabilitat_frau

8. Crear una funció d'anàlisi que indiqui:

    - Quin client té més probabilitat de frau.
    - Quin client té el preu final més alt.
    - Quin client seria prioritari de revisar manualment segons el criteri indicat a l'exercici.

9. Crear la funció `main_asseguradora()` per integrar i coordinar totes les funcions anteriors i mostrar el DataFrame final amb la informació sol·licitada.

### ✔ Preparació de les dades: `clients2`

**Interpretació:** aquesta llista conté les dades inicials proporcionades per la companyia asseguradora. És una **llista de diccionaris**, on cada diccionari representa un client.

Cada client conté:

- `nom`: nom del client.
- `edat`: edat del client.
- `codi`: codi de comportament assignat per la companyia.

Aquest `codi` s'utilitzarà posteriorment per consultar la categoria, el preu base i la probabilitat de frau que corresponen a cada client.

**Idea clau:** el `codi` funciona com a connexió entre cada client i el diccionari `nivells_seguro`.

In [53]:
clients2 = [ 
    {"nom": "Ana", "edat": 42, "codi": 0}, 
    {"nom": "Carlos", "edat": 30, "codi": 2}, 
    {"nom": "Isabel", "edat": 55, "codi": 3}, 
    {"nom": "Jorge", "edat": 40, "codi": 1}, 
    {"nom": "Marta", "edat": 28, "codi": 0} 
]

### ✔ Diccionari `nivells_seguro`

**Interpretació:** aquest diccionari funciona com una taula de consulta proporcionada per la companyia asseguradora.

Cada `codi` identifica un nivell de risc i permet obtenir:

- `categoria`: nivell de risc del client.
- `preu_base`: preu inicial de la pòlissa.
- `fraude`: probabilitat de frau associada al nivell.

**Idea clau:** el valor de `client["codi"]` s'utilitza com a clau per accedir directament a la informació corresponent de `nivells_seguro`, sense necessitat d'utilitzar `if/elif`.

In [54]:
nivells_seguro = { 
    0: {"categoria": "Baix risc", "preu_base": 120, "fraude": 0.01}, 
    1: {"categoria": "Risc mitjà", "preu_base": 200, "fraude": 0.05}, 
    2: {"categoria": "Risc alt", "preu_base": 350, "fraude": 0.15}, 
    3: {"categoria": "Risc crític", "preu_base": 500, "fraude": 0.30} 
}

### ✔ `classificar(p_clients2, p_nivells_seguro)`

**Interpretació:** aquesta funció classifica cada client utilitzant el seu `codi` per consultar la informació corresponent al diccionari `nivells_seguro`.

1. Rebre la llista de clients i el diccionari de nivells de risc.
2. Recórrer cada client amb un `for`.
3. Consultar el valor de `client["codi"]`.
4. Utilitzar aquest codi com a clau de `p_nivells_seguro`.
5. Afegir al diccionari de cada client:
   - `Categoria`
   - `Preu_base`
   - `Probabilitat_frau`
6. Retornar la llista de clients actualitzada.

**Idea clau:** utilitzem el valor d'una clau d'un diccionari (`client["codi"]`) com a clau per accedir a un altre diccionari.

In [55]:
def classificar(p_clients2, p_nivells_seguro):
    for client in p_clients2:
        client["Categoria"] = p_nivells_seguro[client["codi"]]["categoria"]
        client["Preu_base"] = p_nivells_seguro[client["codi"]]["preu_base"]
        client["Probabilitat_frau"] = p_nivells_seguro[client["codi"]]["fraude"]
    return p_clients2

clients2_classificat = classificar(clients2, nivells_seguro)
print(clients2_classificat)

[{'nom': 'Ana', 'edat': 42, 'codi': 0, 'Categoria': 'Baix risc', 'Preu_base': 120, 'Probabilitat_frau': 0.01}, {'nom': 'Carlos', 'edat': 30, 'codi': 2, 'Categoria': 'Risc alt', 'Preu_base': 350, 'Probabilitat_frau': 0.15}, {'nom': 'Isabel', 'edat': 55, 'codi': 3, 'Categoria': 'Risc crític', 'Preu_base': 500, 'Probabilitat_frau': 0.3}, {'nom': 'Jorge', 'edat': 40, 'codi': 1, 'Categoria': 'Risc mitjà', 'Preu_base': 200, 'Probabilitat_frau': 0.05}, {'nom': 'Marta', 'edat': 28, 'codi': 0, 'Categoria': 'Baix risc', 'Preu_base': 120, 'Probabilitat_frau': 0.01}]

### ✔ `preu_final(p_clients2_classificat)`

**Interpretació:** aquesta funció calcula el preu final de la pòlissa de cada client a partir del seu preu base i la seva edat.

1. Rebre la llista de clients ja classificats.
2. Recórrer cada client amb un `for`.
3. Accedir al `Preu_base` i a l'`edat` del client.
4. Aplicar la fórmula:

   `Preu_final = Preu_base * (1 + edat / 100)`

5. Arrodonir el resultat a 2 decimals amb `round()`.
6. Afegir la nova clau `Preu_final` al diccionari de cada client.
7. Retornar la llista actualitzada.

**Idea clau:** cada diccionari es va enriquint amb nova informació sense perdre les dades originals.

In [56]:
def preu_final(p_clients2_classificat):
    for client in p_clients2_classificat:
        client["Preu_final"] = round(client["Preu_base"] * (1 + client["edat"] / 100), 2)
    return p_clients2_classificat

clients2_final = preu_final(clients2_classificat)
print(clients2_final)

[{'nom': 'Ana', 'edat': 42, 'codi': 0, 'Categoria': 'Baix risc', 'Preu_base': 120, 'Probabilitat_frau': 0.01, 'Preu_final': 170.4}, {'nom': 'Carlos', 'edat': 30, 'codi': 2, 'Categoria': 'Risc alt', 'Preu_base': 350, 'Probabilitat_frau': 0.15, 'Preu_final': 455.0}, {'nom': 'Isabel', 'edat': 55, 'codi': 3, 'Categoria': 'Risc crític', 'Preu_base': 500, 'Probabilitat_frau': 0.3, 'Preu_final': 775.0}, {'nom': 'Jorge', 'edat': 40, 'codi': 1, 'Categoria': 'Risc mitjà', 'Preu_base': 200, 'Probabilitat_frau': 0.05, 'Preu_final': 280.0}, {'nom': 'Marta', 'edat': 28, 'codi': 0, 'Categoria': 'Baix risc', 'Preu_base': 120, 'Probabilitat_frau': 0.01, 'Preu_final': 153.6}]

### ✔ Reutilització de `crear_dataframe()`

**Interpretació:** reutilitzem la funció genèrica `crear_dataframe()` creada a l'exercici anterior per transformar la llista de diccionaris en un DataFrame de Pandas.

1. Passar la llista de clients processats a `crear_dataframe()`.
2. Obtenir el DataFrame.
3. Mostrar-lo per comprovar el resultat.

**Idea clau:** no cal tornar a crear una funció si ja tenim una funció genèrica que realitza la mateixa tasca.

In [61]:
df_clients2 = crear_dataframe(clients2_final)
display(df_clients2)

      nom  edat  codi    Categoria  Preu_base  Probabilitat_frau  Preu_final
0     Ana    42     0    Baix risc        120               0.01       170.4
1  Carlos    30     2     Risc alt        350               0.15       455.0
2  Isabel    55     3  Risc crític        500               0.30       775.0
3   Jorge    40     1   Risc mitjà        200               0.05       280.0
4   Marta    28     0    Baix risc        120               0.01       153.6

### ✔ Reutilització de `ordenar_df()`

**Interpretació:** reutilitzem la funció genèrica `ordenar_df()` creada anteriorment per ordenar el DataFrame utilitzant més d'una columna.

En aquest cas, l'ordenació es realitza per:

1. `Probabilitat_frau`.
2. `Preu_final`.

Les columnes es passen com una llista al paràmetre `p_columnes`.

**Idea clau:** com que `ordenar_df()` rep les columnes per paràmetre, la mateixa funció es pot reutilitzar per ordenar diferents DataFrames segons diferents criteris.

In [64]:
df_clients2_ordenat = ordenar_df(df_clients2, ["Probabilitat_frau", "Preu_final"], False)
display(df_clients2_ordenat)

      nom  edat  codi    Categoria  Preu_base  Probabilitat_frau  Preu_final
2  Isabel    55     3  Risc crític        500               0.30       775.0
1  Carlos    30     2     Risc alt        350               0.15       455.0
3   Jorge    40     1   Risc mitjà        200               0.05       280.0
0     Ana    42     0    Baix risc        120               0.01       170.4
4   Marta    28     0    Baix risc        120               0.01       153.6

### ✔ Selecció de les columnes del DataFrame final

**Interpretació:** el DataFrame de treball conté totes les dades dels clients, però el resultat final només ha de mostrar les columnes sol·licitades a l'enunciat.

Es seleccionen:

- `nom`
- `edat`
- `Categoria`
- `Preu_base`
- `Preu_final`
- `Probabilitat_frau`

**Idea clau:** seleccionar columnes no elimina la informació del DataFrame original; simplement crea una vista amb les columnes que volem mostrar.

In [74]:
df_mostra = df_clients2_ordenat[["nom", "edat", "Categoria", "Preu_base", "Preu_final", "Probabilitat_frau"]]
display(df_mostra)

      nom  edat    Categoria  Preu_base  Preu_final  Probabilitat_frau
2  Isabel    55  Risc crític        500       775.0               0.30
1  Carlos    30     Risc alt        350       455.0               0.15
3   Jorge    40   Risc mitjà        200       280.0               0.05
0     Ana    42    Baix risc        120       170.4               0.01
4   Marta    28    Baix risc        120       153.6               0.01

### ✔ `obtenir_maxim(p_df, p_columna)`

**Interpretació:** aquesta funció permet identificar el client o clients que tenen el valor màxim d'una columna determinada.

1. Rebre el DataFrame i el nom de la columna que es vol analitzar.
2. Obtenir el valor màxim de la columna amb `.max()`.
3. Filtrar el DataFrame per conservar totes les files que tenen aquest valor màxim.
4. Seleccionar la columna `nom`.
5. Convertir els noms a una llista amb `.tolist()`.
6. Retornar la llista de noms.

Si diversos clients tenen el mateix valor màxim, la funció retorna tots els clients empatats.

**Idea clau:** la columna s'introdueix com a paràmetre (`p_columna`), per tant la mateixa funció es pot reutilitzar per buscar el màxim de diferents variables.

### Anàlisi dels resultats

A partir del DataFrame final s'analitzen els resultats per respondre les preguntes plantejades per la companyia asseguradora:

1. Identificar el client o clients amb la probabilitat de frau més alta.
2. Identificar el client o clients amb el preu final més alt.
3. Determinar quin client seria prioritari per a una revisió manual.

Per a la revisió manual es considera com a criteri de prioritat la **probabilitat de frau més elevada**.

Per obtenir aquests resultats es reutilitza la funció `obtenir_maxim()`, indicant en cada cas la columna que es vol analitzar.

In [ ]:
def obtenir_maxim(p_df, p_columna):

    maxim = p_df[p_columna].max()
    empatats = p_df[p_df[p_columna] == maxim]
    noms = empatats["nom"].tolist()
    return noms

print(f"El client que té més probabilitat de frau és: {obtenir_maxim(df_clients2_ordenat, "Probabilitat_frau")}")
print(f"El client que té el preu final més alt és: {obtenir_maxim(df_clients2_ordenat, "Preu_final")}")
print(f"Es considera prioritari per a revisió manual el client amb una probabilitat de frau més elevada: {obtenir_maxim(df_clients2_ordenat, "Probabilitat_frau")}")

El client que té més probabilitat de frau és: ['Isabel']
El client que té el preu final més alt és: ['Isabel']
Es considera prioritari per a revisió manual el client amb una probabilitat de frau més elevada: ['Isabel']

## 🧠 Algoritme principal

### ✔ `main_asseguradora()`

**Interpretació:** aquesta és la funció principal que coordina tot el procés de l'exercici. Va passant el resultat d'una funció a la següent fins a obtenir el DataFrame final i l'anàlisi dels clients.

1. Classificar els clients amb `classificar()`.
2. Calcular el preu final amb `preu_final()`.
3. Convertir la llista de clients en DataFrame reutilitzant `crear_dataframe()`.
4. Ordenar el DataFrame reutilitzant `ordenar_df()`.
5. Seleccionar les columnes que demana l'enunciat.
6. Mostrar el DataFrame final.
7. Realitzar l'anàlisi dels resultats utilitzant `obtenir_maxim()`.

**Flux mental:**

`clients2` → `classificar()` → `preu_final()` → `crear_dataframe()` → `ordenar_df()` → seleccionar columnes → mostrar DataFrame → analitzar resultats

**Idea clau:** `main_asseguradora()` coordina el procés, mentre que cada subfunció s'encarrega d'una tasca concreta.

In [82]:
def main_asseguradora():
    clients2_classificat = classificar(clients2, nivells_seguro)
    clients2_final = preu_final(clients2_classificat)
    df_clients2 = crear_dataframe(clients2_final)
    df_clients2_ordenat = ordenar_df(df_clients2, ["Probabilitat_frau", "Preu_final"], False)
    df_mostra = df_clients2_ordenat[["nom", "edat", "Categoria", "Preu_base", "Preu_final", "Probabilitat_frau"]]
    return df_mostra

display(main_asseguradora())

print("APARTAT ANÀLISI:")
print(f"El client que té més probabilitat de frau és: {obtenir_maxim(df_clients2_ordenat, "Probabilitat_frau")}")
print(f"El client que té el preu final més alt és: {obtenir_maxim(df_clients2_ordenat, "Preu_final")}")
print(f"Es considera prioritari per a revisió manual el client amb una probabilitat de frau més elevada: {obtenir_maxim(df_clients2_ordenat, "Probabilitat_frau")}")

      nom  edat    Categoria  Preu_base  Preu_final  Probabilitat_frau
2  Isabel    55  Risc crític        500       775.0               0.30
1  Carlos    30     Risc alt        350       455.0               0.15
3   Jorge    40   Risc mitjà        200       280.0               0.05
0     Ana    42    Baix risc        120       170.4               0.01
4   Marta    28    Baix risc        120       153.6               0.01

APARTAT ANÀLISI:
El client que té més probabilitat de frau és: ['Isabel']
El client que té el preu final més alt és: ['Isabel']
Es considera prioritari per a revisió manual el client amb una probabilitat de frau més elevada: ['Isabel']

# NIVELL 3

## Exercici 2: Processament automàtic de dades esportives

Ara formes part d'un equip d'analítica dins una organització esportiva que gestiona dades de la lliga catalana. La teva companya de feina vol automatitzar la lectura del seu arxiu històric de resultats i extreure les estadístiques més importants. T'ha demanat fer un petit sistema en Python que processi el fitxer 📄 "historic partits.txt"

### 🧠 Algoritme inicial

1. Carregar el fitxer `historic_partits.txt` en un DataFrame.

2. Preparar les dades amb la funció `preparar_dades()`:
   - Assignar els noms de les columnes:
     `equip_local`, `resultat`, `equip_visitant`.
   - Separar `resultat` en `gols_local` i `gols_visitant`.
   - Convertir els gols a tipus enter.
   - Retornar `df_partits_net`.

3. Calcular les estadístiques amb la funció `estadistics()`:
   - Calcular els gols a favor com a local i visitant.
   - Calcular els gols totals a favor.
   - Calcular els gols en contra com a local i visitant.
   - Calcular els gols totals en contra.
   - Identificar i comptar les victòries com a local i visitant.
   - Calcular les victòries totals.
   - Identificar i comptar les derrotes com a local i visitant.
   - Calcular les derrotes totals.
   - Identificar els empats.
   - Comptar els empats com a local i visitant.
   - Calcular els empats totals.
   - Crear `df_estadistiques` amb:
        - `gols_favor`
        - `gols_contra`
        - `guanyats`
        - `empatats`
        - `perduts`
   - Calcular la columna `punts`:
        - victòria = 3 punts
        - empat = 1 punt
        - derrota = 0 punts.
   - Retornar `df_estadistiques`.

4. Ordenar la classificació:
   - Reutilitzar la funció `ordenar_df()` creada anteriorment.
   - Ordenar `df_estadistiques` per `punts` de major a menor.

5. Respondre les preguntes de l'enunciat mitjançant funcions separades:
   - Obtenir l'equip o equips més golejadors.
   - Obtenir l'equip o equips més golejats.
   - Mostrar el total de gols de cada equip.
   - Mostrar la classificació final.

6. Crear una funció principal que orquestri tot el procés:
   - Preparar les dades.
   - Calcular les estadístiques.
   - Ordenar la classificació.
   - Cridar les funcions que responen les preguntes.
   - Mostrar els resultats.

### Càrrega i visualització inicial de les dades

**Interpretació:** primer carreguem el fitxer `historic_partits.txt` en un DataFrame per observar com estan organitzades les dades abans de començar a transformar-les.

1. Llegim el fitxer amb `pd.read_csv()`.
2. Indiquem `sep="\t"` perquè les dades estan separades per tabulacions.
3. Indiquem `header=None` perquè el fitxer original no conté noms de columnes.
4. Mostrem les primeres files amb `.head()` per comprovar l'estructura de les dades.
5. Consultem els tipus de dades amb `.dtypes`.

**Idea clau:** abans de transformar unes dades és important visualitzar-les i comprovar com estan estructurades i quin tipus de dades conté cada columna.

In [149]:
df_partits = pd.read_csv("historic_partits.txt", sep="\t", header=None)

display(df_partits.head(10))

display(df_partits.dtypes)

              0    1           2
0       Manlleu  0-1  Granollers
1    Vilafranca  4-5    Terrassa
2          Olot  5-0  Granollers
3    Vilafranca  5-5     Manlleu
4      Cornellà  5-1        Prat
5    Cerdanyola  0-5  Vilafranca
6   Sant Andreu  2-3    Cornellà
7    Vilafranca  5-4        Olot
8  FC Barcelona  4-4    Badalona
9    Granollers  1-5    Sabadell

0    object
1    object
2    object
dtype: object

### ✔ `preparar_dades(p_df)`

**Interpretació:** aquesta funció prepara les dades originals perquè després puguem realitzar els càlculs dels partits. Assigna noms a les columnes, separa el resultat del partit en gols locals i visitants i converteix aquests valors a nombres enters.

1. Rep com a paràmetre el DataFrame original.
2. Assigna els noms `equip_local`, `resultat` i `equip_visitant` a les tres columnes originals.
3. Selecciona la columna `resultat`.
4. Utilitza `.str.split("-", expand=True)` per separar resultats com `"3-1"` en dos valors diferents.
5. Guarda aquests valors en les noves columnes `gols_local` i `gols_visitant`.
6. Converteix les dues columnes de gols a tipus `int` mitjançant `.astype(int)`.
7. Retorna el DataFrame preparat.

**Idea clau:** `.str.split()` permet dividir el text d'una columna utilitzant un separador. Amb `expand=True`, Pandas col·loca cada part del resultat en una columna diferent.

In [110]:
def preparar_dades(p_df):
    p_df.columns = ["equip_local", "resultat", "equip_visitant"]
    p_df[["gols_local", "gols_visitant"]] = p_df["resultat"].str.split("-", expand=True)
    p_df[["gols_local", "gols_visitant"]] = p_df[["gols_local", "gols_visitant"]].astype(int)
    return p_df

df_partits_net = preparar_dades(df_partits)
display(df_partits_net)
display(df_partits_net.dtypes)

             equip_local resultat equip_visitant  gols_local  gols_visitant
0                Manlleu      0-1     Granollers           0              1
1             Vilafranca      4-5       Terrassa           4              5
2                   Olot      5-0     Granollers           5              0
3             Vilafranca      5-5        Manlleu           5              5
4               Cornellà      5-1           Prat           5              1
..                   ...      ...            ...         ...            ...
495  Nàstic de Tarragona      1-3           Olot           1              3
496             Badalona      5-4           Prat           5              4
497                 Olot      4-5     Llagostera           4              5
498         FC Barcelona      3-1       Cornellà           3              1
499                 Olot      0-5     Granollers           0              5

[500 rows x 5 columns]

equip_local       object
resultat          object
equip_visitant    object
gols_local         int64
gols_visitant      int64
dtype: object

### ✔ `estadistics(p_df)`

**Interpretació:** aquesta funció calcula les estadístiques de cada equip a partir dels partits jugats com a local i com a visitant. Finalment, agrupa els resultats en un nou DataFrame on cada fila representa un equip.

#### Gols a favor

1. Agrupem els partits per `equip_local`.
2. Sumem `gols_local` per obtenir els gols marcats per cada equip quan juga com a local.
3. Agrupem els partits per `equip_visitant`.
4. Sumem `gols_visitant` per obtenir els gols marcats quan juga com a visitant.
5. Sumem les dues Series per obtenir els gols totals a favor de cada equip.

**Idea clau:** `groupby()` agrupa les files que pertanyen al mateix equip i `.sum()` suma els valors de cada grup. Quan sumem dues Series, Pandas les relaciona utilitzant el seu índex, que en aquest cas és el nom de l'equip.


#### Gols en contra

1. Agrupem per `equip_local` i sumem `gols_visitant`, ja que són els gols que el local ha rebut.
2. Agrupem per `equip_visitant` i sumem `gols_local`, ja que són els gols que el visitant ha rebut.
3. Sumem les dues Series per obtenir els gols totals en contra de cada equip.

**Idea clau:** per calcular els gols en contra hem de mirar els gols marcats per l'equip contrari. La columna que utilitzem depèn de si l'equip està jugant com a local o com a visitant.


#### Partits guanyats

1. Filtrem els partits on `gols_local > gols_visitant` per obtenir les victòries dels equips locals.
2. Agrupem aquests partits per `equip_local`.
3. Utilitzem `.size()` per comptar quants partits ha guanyat cada equip com a local.
4. Filtrem els partits on `gols_local < gols_visitant` per obtenir les victòries dels equips visitants.
5. Agrupem aquests partits per `equip_visitant` i els comptem amb `.size()`.
6. Sumem les victòries locals i visitants per obtenir el total de partits guanyats de cada equip.

**Idea clau:** primer filtrem les files que compleixen una condició i després les agrupem. `.size()` compta el nombre de files de cada grup; com cada fila representa un partit, obtenim el nombre de victòries.


#### Partits perduts

1. Filtrem els partits on `gols_local < gols_visitant` per identificar les derrotes dels equips locals.
2. Agrupem per `equip_local` i comptem els partits amb `.size()`.
3. Filtrem els partits on `gols_local > gols_visitant` per identificar les derrotes dels equips visitants.
4. Agrupem per `equip_visitant` i comptem els partits amb `.size()`.
5. Sumem les derrotes com a local i com a visitant.

**Idea clau:** la mateixa condició pot representar una victòria o una derrota depenent de quin equip estiguem analitzant. Si `gols_local > gols_visitant`, el local ha guanyat però el visitant ha perdut.


#### Partits empatats

1. Filtrem els partits on `gols_local == gols_visitant`.
2. Agrupem els empats per `equip_local` i els comptem amb `.size()`.
3. Agrupem els mateixos empats per `equip_visitant` i els comptem amb `.size()`.
4. Sumem els empats locals i visitants per obtenir el total d'empats de cada equip.

**Idea clau:** un mateix partit empatat compta com un empat per als dos equips. Per això comptem l'equip local i el visitant per separat i després sumem els resultats.

### Creació de `df_estadistiques`

**Interpretació:** després de calcular les diferents estadístiques, les agrupem en un únic DataFrame. A `df_partits_net` cada fila representa un partit, mentre que a `df_estadistiques` cada fila representa un equip.

1. Creem un DataFrame buit amb `pd.DataFrame()`.
2. Afegim la columna `gols_favor` amb els gols totals a favor.
3. Afegim la columna `gols_contra` amb els gols totals en contra.
4. Afegim la columna `guanyats` amb les victòries totals.
5. Afegim la columna `empatats` amb els empats totals.
6. Afegim la columna `perduts` amb les derrotes totals.
7. Pandas utilitza l'índex de les Series, format pels noms dels equips, per relacionar correctament els valors.

**Idea clau:** podem construir un DataFrame afegint Series com a columnes. Pandas les alinea segons el seu índex, de manera que les estadístiques corresponents al mateix equip queden a la mateixa fila.


### Càlcul dels punts

**Interpretació:** una vegada tenim les victòries i els empats de cada equip, podem calcular directament els punts de la classificació i guardar-los en una nova columna.

1. Multipliquem el nombre de partits guanyats per `3`.
2. Cada empat aporta `1` punt, per tant sumem directament la columna `empatats`.
3. Les derrotes aporten `0` punts i no és necessari incloure-les en el càlcul.
4. Guardem el resultat en una nova columna anomenada `punts`.
5. Retornem `df_estadistiques` amb totes les estadístiques calculades.

**Fórmula:**

`punts = (guanyats × 3) + empatats`

**Idea clau:** Pandas permet realitzar operacions matemàtiques directament entre columnes. El càlcul s'aplica automàticament a totes les files, per tant no és necessari utilitzar un bucle ni `.apply()`.

In [126]:
def estadistics(p_df):

    # GOLS A FAVOR
    gols_local_favor = p_df.groupby("equip_local")["gols_local"].sum()
    gols_visitant_favor = p_df.groupby("equip_visitant")["gols_visitant"].sum()
    gols_totals_favor = gols_local_favor + gols_visitant_favor

    # GOLS EN CONTRA
    gols_local_contra = p_df.groupby("equip_local")["gols_visitant"].sum()
    gols_visitant_contra = p_df.groupby("equip_visitant")["gols_local"].sum()
    gols_totals_contra = gols_local_contra + gols_visitant_contra

    # GUANYATS
    guanyats_local = p_df[p_df["gols_local"] > p_df["gols_visitant"]]
    total_guanyats_local = guanyats_local.groupby("equip_local").size()
    guanyats_visitant = p_df[p_df["gols_local"] < p_df["gols_visitant"]]
    total_guanyats_visitant = guanyats_visitant.groupby("equip_visitant").size()
    total_guanyats = total_guanyats_local + total_guanyats_visitant

    # PERDUTS
    perduts_local = p_df[p_df["gols_local"] < p_df["gols_visitant"]]
    total_perduts_local = perduts_local.groupby("equip_local").size()
    perduts_visitant = p_df[p_df["gols_local"] > p_df["gols_visitant"]]
    total_perduts_visitant = perduts_visitant.groupby("equip_visitant").size()
    total_perduts = total_perduts_local + total_perduts_visitant

    # EMPATS
    empats = p_df[p_df["gols_local"] == p_df["gols_visitant"]]
    total_empats_local = empats.groupby("equip_local").size()
    total_empats_visitant = empats.groupby("equip_visitant").size()
    total_empats = total_empats_local + total_empats_visitant

    # CREAR DF
    df_estadistiques = pd.DataFrame()
    df_estadistiques["gols_favor"] = gols_totals_favor
    df_estadistiques["gols_contra"] = gols_totals_contra
    df_estadistiques["guanyats"] = total_guanyats
    df_estadistiques["empatats"] = total_empats
    df_estadistiques["perduts"] = total_perduts

    # PUNTS
    df_estadistiques["punts"] = (df_estadistiques["guanyats"] * 3) + (df_estadistiques["empatats"])

    # CANVIAR NOM DE L'ÍNDEX
    df_estadistiques.index.name = "equip"

    return df_estadistiques

df_estadistiques = estadistics(df_partits_net)
display(df_estadistiques)

,gols_favor,gols_contra,guanyats,empatats,perduts,punts
equip,,,,,,
Badalona,134,124,18,14,16,68
Cerdanyola,117,133,17,5,28,56
Cornellà,147,146,25,7,22,82
Europa,93,93,12,5,16,41
FC Barcelona,125,115,22,7,15,73
Figueres,161,154,23,10,23,79
Girona FC,139,94,31,3,13,96
Granollers,122,117,21,4,24,67
Llagostera,159,142,29,7,20,94
Lleida Esportiu,129,133,23,6,23,75
Manlleu,106,118,16,9,18,57
Nàstic de Tarragona,130,148,20,8,27,68
Olot,132,144,18,10,26,64
Prat,106,111,16,8,21,56
RCD Espanyol,131,144,23,11,21,80
Reus Deportiu,119,111,20,8,16,68
Sabadell,141,121,26,7,15,85
Sant Andreu,123,134,17,11,25,62
Terrassa,147,164,20,14,23,74
Vilafranca,157,172,20,12,25,72

### Ordenació de la classificació

**Interpretació:** una vegada calculades totes les estadístiques dels equips, ordenem el DataFrame segons la columna `punts` per obtenir la classificació de major a menor puntuació.

1. RE-utilitzem una funció ja creada, la qual rep el DataFrame que volem ordenar.
2. Indiquem la columna `punts` com a criteri d'ordenació.
3. Utilitzem `ascending=False` perquè volem ordenar els punts de major a menor.
4. Guardem el resultat en un nou DataFrame ordenat.

**Idea clau:** `.sort_values()` permet ordenar un DataFrame segons els valors d'una o diverses columnes.

- `ascending=True` → de menor a major.
- `ascending=False` → de major a menor.

En aquest exercici utilitzem `False` perquè l'equip amb més punts ha d'aparèixer primer a la classificació.

In [139]:
df_estadistiques_ordenat = ordenar_df(df_estadistiques, "punts", p_ascendent=False)
display(df_estadistiques_ordenat)

,gols_favor,gols_contra,guanyats,empatats,perduts,punts
equip,,,,,,
Girona FC,139,94,31,3,13,96
Llagostera,159,142,29,7,20,94
Sabadell,141,121,26,7,15,85
Cornellà,147,146,25,7,22,82
RCD Espanyol,131,144,23,11,21,80
Figueres,161,154,23,10,23,79
Lleida Esportiu,129,133,23,6,23,75
Terrassa,147,164,20,14,23,74
FC Barcelona,125,115,22,7,15,73
Vilafranca,157,172,20,12,25,72
Badalona,134,124,18,14,16,68
Reus Deportiu,119,111,20,8,16,68
Nàstic de Tarragona,130,148,20,8,27,68
Granollers,122,117,21,4,24,67
Olot,132,144,18,10,26,64
Sant Andreu,123,134,17,11,25,62
Manlleu,106,118,16,9,18,57
Cerdanyola,117,133,17,5,28,56
Prat,106,111,16,8,21,56
Europa,93,93,12,5,16,41

### Equip més golejador

**Interpretació:** busquem l'equip o equips que han marcat més gols durant tots els partits.

1. Utilitzem `.max()` sobre la columna `gols_favor` per obtenir el nombre màxim de gols marcats.
2. Comparem tots els valors de `gols_favor` amb aquest màxim.
3. La comparació genera una sèrie de valors `True` i `False`.
4. Utilitzem aquesta condició per filtrar el DataFrame.
5. D'aquesta manera obtenim l'equip o equips que tenen el màxim nombre de gols a favor.

**Idea clau:** en lloc d'agafar simplement la primera fila, filtrem utilitzant el valor màxim. Això permet obtenir tots els equips en cas que hi hagi un empat.

Patró utilitzat:

`df[df["columna"] == df["columna"].max()]`

In [134]:
def equip_golejador(p_df_estadistiques):
    equip_golejador = p_df_estadistiques[p_df_estadistiques["gols_favor"] == p_df_estadistiques["gols_favor"].max()]
    print("L'equip més golejador és:")
    display(equip_golejador[["gols_favor"]])

equip_golejador(df_estadistiques)

L'equip més golejador és:

          gols_favor
equip
Figueres         161

### Equip més golejat

**Interpretació:** busquem l'equip o equips que han rebut més gols durant tots els partits.

1. Utilitzem `.max()` sobre la columna `gols_contra` per obtenir el nombre màxim de gols rebuts.
2. Comparem tots els valors de `gols_contra` amb aquest valor màxim.
3. La comparació genera una sèrie de valors `True` i `False`.
4. Utilitzem aquesta condició per filtrar el DataFrame.
5. D'aquesta manera obtenim l'equip o equips que tenen el màxim nombre de gols en contra.

**Idea clau:** utilitzem el mateix patró que per trobar l'equip més golejador, però en aquest cas consultem la columna `gols_contra`.

In [ ]:
def equip_golejat(p_df_estadistiques):
    equip_golejat = p_df_estadistiques[p_df_estadistiques["gols_contra"] == p_df_estadistiques["gols_contra"].max()]
    print("L'equip més golejat és:")
    display(equip_golejat[["gols_contra"]])

equip_golejat(df_estadistiques)

L'equip més golejat és:

            gols_contra
equip
Vilafranca          172

### Total de gols de cada equip

**Interpretació:** mostrem el nombre total de gols marcats per cada equip.

Aquest càlcul ja s'ha realitzat anteriorment dins de la funció `estadistics()`, on els gols marcats com a local i com a visitant s'han sumat i s'han guardat a la columna `gols_favor`.

Per tant, no és necessari tornar a calcular els gols. Només seleccionem la columna `gols_favor` del DataFrame d'estadístiques.

**Idea clau:** si una dada ja ha estat calculada i guardada al DataFrame, podem reutilitzar-la en lloc de repetir el càlcul.

In [137]:
def total_gols(p_df_estadistiques):
    total_gols = p_df_estadistiques[["gols_favor"]]
    print("El nombre total de gols de cada equip és:")
    display(total_gols)

total_gols(df_estadistiques)

El nombre total de gols de cada equip és:

                     gols_favor
equip
Badalona                    134
Cerdanyola                  117
Cornellà                    147
Europa                       93
FC Barcelona                125
Figueres                    161
Girona FC                   139
Granollers                  122
Llagostera                  159
Lleida Esportiu             129
Manlleu                     106
Nàstic de Tarragona         130
Olot                        132
Prat                        106
RCD Espanyol                131
Reus Deportiu               119
Sabadell                    141
Sant Andreu                 123
Terrassa                    147
Vilafranca                  157

### Classificació final

**Interpretació:** preparem la classificació final a partir del DataFrame que ja està ordenat per punts.

1. La funció rep el DataFrame d'estadístiques ordenat de major a menor puntuació.
2. En aquest DataFrame, els noms dels equips es troben a l'índex.
3. Utilitzem `.reset_index()` per convertir l'índex `equip` en una columna normal.
4. En fer `reset_index()`, Pandas crea automàticament un nou índex numèric que comença per `0`.
5. Seleccionem únicament les columnes `equip` i `punts`, que són les dades necessàries per mostrar la classificació.
6. Sumem `1` al nou índex perquè les posicions comencin per `1` en lloc de `0`.
7. Mostrem el DataFrame final.

**Idea clau:** `.reset_index()` converteix l'índex actual en una columna i crea un nou índex numèric.

En aquest cas aprofitem aquest nou índex per representar la posició de cada equip:

`0, 1, 2, 3...` → `1, 2, 3, 4...`

In [147]:
def classificació_final(p_df_estadistiques_ordenat):

    classificacio_final = p_df_estadistiques_ordenat.reset_index()
    classificacio_final = classificacio_final[["equip", "punts"]]
    classificacio_final.index = classificacio_final.index + 1

    print("La classificació final és:")
    display(classificacio_final)


classificació_final(df_estadistiques_ordenat)

La classificació final és:

                  equip  punts
1             Girona FC     96
2            Llagostera     94
3              Sabadell     85
4              Cornellà     82
5          RCD Espanyol     80
6              Figueres     79
7       Lleida Esportiu     75
8              Terrassa     74
9          FC Barcelona     73
10           Vilafranca     72
11             Badalona     68
12        Reus Deportiu     68
13  Nàstic de Tarragona     68
14           Granollers     67
15                 Olot     64
16          Sant Andreu     62
17              Manlleu     57
18           Cerdanyola     56
19                 Prat     56
20               Europa     41

## 🧠 Algoritme principal

### ✔ `main()`

**Interpretació:** aquesta és la funció principal que coordina tot el procés de l'exercici. Va passant el resultat d'una funció a la següent fins a obtenir les estadístiques dels equips, ordenar la classificació i mostrar els resultats demanats.

1. Preparar les dades dels partits amb `preparar_dades()`.
2. Calcular les estadístiques de cada equip amb `estadistics()`.
3. Ordenar el DataFrame d'estadístiques per punts reutilitzant `ordenar_df()`.
4. Mostrar l'equip o equips més golejadors.
5. Mostrar l'equip o equips més golejats.
6. Mostrar el total de gols de cada equip.
7. Mostrar la classificació final amb els equips ordenats per punts.

**Flux mental:**

`df_partits` → `preparar_dades()` → `estadistics()` → `ordenar_df()` → mostrar resultats → `classificació_final()`

**Idea clau:** `main()` coordina tot el procés, mentre que cada subfunció s'encarrega d'una tasca concreta.

In [150]:
def main_partits():
    
    df_partits_net = preparar_dades(df_partits)
    df_estadistiques = estadistics(df_partits_net)
    df_estadistiques_ordenat = ordenar_df(df_estadistiques, "punts", p_ascendent=False)
    equip_golejador(df_estadistiques)
    equip_golejat(df_estadistiques)
    total_gols(df_estadistiques)
    classificació_final(df_estadistiques_ordenat)


main_partits()

L'equip més golejador és:

          gols_favor
equip
Figueres         161

L'equip més golejat és:

            gols_contra
equip
Vilafranca          172

El nombre total de gols de cada equip és:

                     gols_favor
equip
Badalona                    134
Cerdanyola                  117
Cornellà                    147
Europa                       93
FC Barcelona                125
Figueres                    161
Girona FC                   139
Granollers                  122
Llagostera                  159
Lleida Esportiu             129
Manlleu                     106
Nàstic de Tarragona         130
Olot                        132
Prat                        106
RCD Espanyol                131
Reus Deportiu               119
Sabadell                    141
Sant Andreu                 123
Terrassa                    147
Vilafranca                  157

La classificació final és:

                  equip  punts
1             Girona FC     96
2            Llagostera     94
3              Sabadell     85
4              Cornellà     82
5          RCD Espanyol     80
6              Figueres     79
7       Lleida Esportiu     75
8              Terrassa     74
9          FC Barcelona     73
10           Vilafranca     72
11             Badalona     68
12        Reus Deportiu     68
13  Nàstic de Tarragona     68
14           Granollers     67
15                 Olot     64
16          Sant Andreu     62
17              Manlleu     57
18           Cerdanyola     56
19                 Prat     56
20               Europa     41